services:
  backend:
    build: ./backend
    restart: unless-stopped
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URI:-postgresql://postgres:postgres@host.docker.internal:6432/bigdata}

  frontend:
    build: ./frontend
    restart: unless-stopped
    network_mode: host
